title: "Southeast Region | U.S. Fish and Wildlife Service"

MetaDataFormat: yaml
pluralizelisttitles: false
relativeURLS: true
publishDir: '../dist'

mediaTypes:
  application/javascript:
    suffixes: ["js"]

outputFormats:
  js:
    suffix: js
    mediaType: application/javascript
    isPlainText: true
    isHTML: false
    noUgly: false
    baseName: index
    rel: alternate

googleAnalytics: UA-21323598-1

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

outputs:
  home:
    - html
    - rss
    - js
  page:
    - html
  section:
    - html
    - rss
    - js

# Custom Defined Site Wide Variables
params:
  hero:
  twitter: usfwssoutheast
  github:  usfws
  facebook: usfwssoutheast
  flickr: usfwssoutheast
  snapchat: usinterior
  instagram: usfws
  youtube: https://www.youtube.com/playlist?list=PL5225C01A38A652EA&feature=plcp
  webmaster:
    primary: roy_hewitt@fws.gov
    backup: katherine_taylor@fws.gov

permalinks:
  news: /:section/:year/:month/:filename/
  podcasts: /:section/:year/:month/:filename/
