baseurl: "http://replace-this-with-your-hugo-site.com/"
lang: "en-us"
title: "Southeast Region | U.S. Fish and Wildlife Service"

pluralizelisttitles: false
canonifyurls: true

# Custom Defined Site Wide Variables
params:
  hero:
  analytics: UA-21323598-1
  twitter: usfwssoutheast
  github:  usfws
  facebook: usfwssoutheast
  flickr: usfwssoutheast
  instagram: usfws
  webmaster:
    primary: roy_hewitt@fws.gov
    backup: jennifer_strickland@fws.gov

permalinks:
  news: /:section/:year/:month/:filename/
...
