baseurl: "http://fws.gov/southeast/"
title: "Southeast Region | U.S. Fish and Wildlife Service"

pluralizelisttitles: false
canonifyurls: true

googleAnalytics: UA-21323598-1

taxonomies:
  tag: "tags"
  category: "categories"

# Custom Defined Site Wide Variables
params:
  hero:
  twitter: usfwssoutheast
  github:  usfws
  facebook: usfwssoutheast
  flickr: usfwssoutheast
  instagram: usfws
  webmaster:
    primary: roy_hewitt@fws.gov
    backup: jennifer_strickland@fws.gov

permalinks:
  news: /:section/:year/:month/:filename/
...
